config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 authenticated :user do
  root :to => 'entries#index', as: :authenticated_root
end
root :to => 'pages#home'

  resources :entries, only: [:create, :destroy, :index] do
    resources :updates, only: [:create]
 end
 get '/demo' => 'entries#demo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :updates, dependent: :destroy

end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :entry
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/entries_controller.rb
require 'date'
class EntriesController < ApplicationController

  def demo
    @entry = Entry.new
    @update = Update.new
  end

  def index
    @entry = Entry.new
    @entries = Entry.all
    @user = current_user
    @update = Update.new
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { head :no_content }
    end
  end


  def create
    @entry = Entry.new(entry_params)
    @entry.date = Date.today.strftime
    @entry.user = current_user

    if
      @entry.save
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:date, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController


  def create
    @update = Update.new(update_params)
    @entry = Entry.find(params[:entry_id])
    @update.entry = @entry
    @update.date = Date.today.strftime

    if @update.save
      p 'saved'
    else
      p 'not saved'
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { head :no_content }
    end

  end

  private

  def update_params
    params.require(:update).permit(:body, :date)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/entries/demo.html.erb
<div class="carousel-wrapper">
  <div class="carousel">
    <div class="carousel__entry">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">
            <div class="entries">
              <%= render :partial => 'shared/demo-dropdown' %>
              <div class="button-wrapper " style="display:none">
                <div class="carousel__button--next"></div>
                <div class="carousel__button--prev"></div>
              </div>
              <div class="title">
              <div class="subtitle">
                    <span >The Simple Diary</span>

              </div>
                <div class="date">
                    <% date = Time.now.to_s %>
                   <%= Date.parse(date).strftime("%m/%d/%Y")%>
                </div>
              </div>
              <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div id="demo-entry">
                <div contenteditable="true" class="entry">
                  <p class="tab">&nbsp;</p>
                </div>
              </div>
              <div class="margin"></div>
              <div class="count">
                <p>- 1 -</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <span class="box1 ">Welcome to The Simple Diary's demonstration.Type something to continue...</span>

    <span class="box2 sb2 ">Great! The 3 dots in the top corner are the dropdown
    Try clicking them and pressing save.</span>

    <span class="box3 sb3 ">Your entry is now saved. When you have more than one entry
    you can cycle through them by the arrows on the top right of the entry.</span>

    <span class="box4">All done. You can now <%= link_to "return home", root_path,
     class: "link-styling" %>
      to log-in/sign-up
    </span>

    <div class="carousel__entry">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 md-12 col-lg-6 col-lg-offset-3">
            <div class="about-entry">
              <!-- This is the dropdown for each page -->
              <%= render :partial => 'shared/demo-dropdown' %>
              <div class="button-wrapper">
                <div class="carousel__button--next"></div>
                <div class="carousel__button--prev"></div>
              </div>
              <div class="title">

                <div class="subtitle">
                    <span>The Simple Diary</span>

                </div>
                <div class="date">
                    06/10/2020
                </div>
              </div>
                  <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div class="entry">
                <p style="font-size: 14px">
                  If you have any comments or questions, feel free to email thesimplediary@yahoo.com
                </p>
              <div class="count">
                <p>-0-</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entries/home.html.erb
    <% date = Date.today.strftime %>
    <% if !user_signed_in? %>
      <%= render :partial => 'shared/logged-out' %>
    <% elsif user_signed_in? && !@user.entries.exists? %>
      <%= render :partial => 'shared/zero-entries' %>
    <% elsif @user.entries.first.date == date  && @user.entries.count == 1%>
      <% @user.entries.each_with_index do |entry, index|  %>
        <%= render :partial => 'shared/one-entry', locals: {entry: entry, index: index}  %>
        <%= render :partial => 'shared/update-form' %>
      <% end %>
    <% else %>
      <%= render :partial => 'shared/many-entries', locals: {date: date}  %>
    <% end %>

app/views/entries/index.html.erb
    <% date = Date.today.strftime %>
    <% if !@user.entries.exists? %>
      <%= render :partial => 'shared/zero-entries' %>
    <% elsif @user.entries.first.date == date  && @user.entries.count == 1%>
      <% @user.entries.each_with_index do |entry, index|  %>
        <%= render :partial => 'shared/one-entry', locals: {entry: entry, index: index}  %>
        <%= render :partial => 'shared/update-form' %>
      <% end %>
    <% else %>
      <%= render :partial => 'shared/many-entries', locals: {date: date}  %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Simple Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('book.png')%>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
  <!-- code only runs if todays entry hasnt been made -->

      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 col-lg-6 col-lg-offset-3">
            <div class="entries">
            <div class="title">
              <div class="subtitle" style="margin-top: 40px">
                    <span>The Simple Diary</span>
              </div>
              <div class="date">

                    <% date = Time.now.to_s %>
                    <%= Date.parse(date).strftime("%m/%d/%Y")%>

              </div>
            </div>
              <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div class="entry">
                <p id="demo-text">

                </p>
              </div>
              <div class="margin"></div>
              <div class="count">
                <p>- 1 -</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class='home_page_button_wrapper'>
        <span><%= link_to 'Demo', demo_path, class: "wrapper_buttons demo_button" %></span>
        <span> <%= link_to 'Log-in', user_session_path, class: "wrapper_buttons log_in_button" %>
        </span>
      </div>

app/views/shared/_demo-dropdown.html.erb
<div class="dropdown">
  <div class="ellipses">
    <span class="fas fa-ellipsis-v"> </span>
  </div>
  <div class="dropdown-child">
    <a class="dropdown-item" id="demo-save">Save</a>
  </div>
</div>

app/views/shared/_dropdown.html.erb
<!-- This is the dropdown for each page -->
  <div class="dropdown">
    <div class="ellipses">
     <span class="fas fa-ellipsis-v"> </span>
      </div>
      <div class="dropdown-child">
        <!-- delete will only show on existing entries -->
            <% if entry %>
              <a><%= link_to "Delete", entry_path(entry.id), method: :delete, data: {confirm: "Are you sure?"}, class: "dropdown-item delete", style: "display:none" %></a>
            <% end %>
            <a class="dropdown-item edit" style="display:none">Update</a>
            <a class="dropdown-item save" style="display:none">Save</a>
            <a class="dropdown-item cancel" style="display:none">Cancel</a>
            <a class="dropdown-item hyphen">--</a>
          <a><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></a>
      </div>
  </div>

app/views/shared/_logged-out.html.erb
<div class="carousel-wrapper">
  <div class="carousel">
    <div class="carousel__entry">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">
            <div class="entries">
              <div class="button-wrapper">
                  <div class="carousel__button--next"></div>
                  <div class="carousel__button--prev"></div>
              </div>
              <div class="title" style="margin-top: 20px;">
                <div class="subtitle">

                    <%= link_to "Log-in", user_session_path %>
                    to save entries
                </div>
                <div class="date">
                    <% date = Time.now.to_s %>
                   <%= Date.parse(date).strftime("%m/%d/%Y")%>
                </div>
              </div>
              <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div contenteditable="true" class="entry">
                <p class="tab" onclick="">&nbsp;</p>
              </div>
              <div class="margin"></div>
              <div class="count">
                <p>- 1 -</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="carousel__entry">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 md-12 col-lg-6 col-lg-offset-3">
            <div class="about-entry">
              <div class="button-wrapper">
                <div class="carousel__button--next"></div>
                <div class="carousel__button--prev"></div>
              </div>
              <div class="title" style="margin-top: 20px;">

                <div class="subtitle">
                      About
                </div>
                <div class="date">
                    06/10/2020
                </div>
              </div>
                  <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div class="entry">
                <p style="font-size: 1.3rem">Welcome to The Simple Diary, a diary app
                 designed to be simple and intuitive.
                  <br>
                  <br>
                  <br>
                  The app was created because I had grown tired of using text editors to record things
                  and having to manually time-stamp and name everything; I figured it would be better
                  to have something do this for me. I looked into other diary apps but they were all
                  over-engineered and bloated with unnecessary features that made them frustrating and
                  counter-intuitive to use. As you'll notice, there are virtually no links anywhere
                  on the page, just the document for text entry. There are also only 2 features,
                  saving and updating an entry. The update feature allows you to come back to a
                  post and add a comment to it, with the comment getting time-stamped automatically.
                  <br>
                  <br>
                  <br>
                  The Simple Diary was designed primarily for desktop use,
                  however it will work on hand-held devices.
                  <br>
                  <br>
                  If you have any comments or questions, feel free to email thesimplediary@yahoo.com
                </p>
              <div class="count">
                <p>-0-</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_many-entries.html.erb
<% @make_new = true %>
<% @user.entries.each do |entry| %>
  <% if entry.date == date%>
  <!-- looks through database, if today's entry has been made, made variable is set to false -->
    <% @make_new = false  %>
    <% break %>
  <% end %>
  <% end %>

<div class="carousel-wrapper">


  <div class="carousel">
    <% if (@make_new) %>
    <!-- code only runs if todays entry hasnt been made -->
      <div class="carousel__entry">
        <%= render :partial => 'shared/zero-entries' %>
      </div>
    <% end %>

    <% @user.entries.each_with_index do |entry, index| %>
      <div class="carousel__entry">
        <%= render :partial => 'shared/one-entry', locals: {entry: entry, index: index} %>
      </div>
    <% end %>
    <%= render :partial => 'shared/update-form' %>
  </div>
</div>

app/views/shared/_new-dropdown.html.erb
<!-- This is the dropdown for each page -->
  <div class="dropdown">
    <div class="ellipses">
     <span class="fas fa-ellipsis-v"> </span>
      </div>
      <div class="dropdown-child">
        <!-- delete will only show on existing entries -->
            <a class="dropdown-item" id="save">Save</a>
            <a class="dropdown-item hyphen">--</a>

          <a><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></a>
      </div>
  </div>

app/views/shared/_one-entry.html.erb
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12 md-12 col-lg-6 col-lg-offset-3">
          <div class="entries">
            <%= render :partial => 'shared/dropdown', locals: {entry: entry} %>
         <div class="button-wrapper">
          <div class="carousel__button--next"></div>
          <div class="carousel__button--prev"></div>
        </div>
          <div class="title">
            <div class="subtitle">
                  <%= @user.name.capitalize %>'s Diary
            </div>
            <div class="date">
                <% date = entry.date %>
                <%= Date.parse(date).strftime("%m/%d/%Y")%>
            </div>
          </div>
            <div class="divider div-transparent div-dot"></div>
            <!-- This is where you enter text  -->
            <div class="entry">
              <%= entry.body.html_safe %>
            </div>
            <div id="update-<%=entry.id%>">
              <div class="updates">
              <% if entry.updates.exists? %>
                <% sorted_updates = entry.updates.sort_by(&:created_at) %>
                <% sorted_updates.each do |update| %>
                  <% update_date = update.date %>
                  <% update_date = Date.parse(update_date).strftime("%m/%d/%Y") %>
                  <p class="update-date ">Updated on <%= update_date %></p>
                  <p class="entry-updates spacing"> <%= update.body.html_safe %></p>
                <% end %>
              <% end %>
              </div>
            </div>
            <div class="toggle">
                <div class="divider div-transparent"></div>
              <div contenteditable="true" class="update-entry update-padding">
                &nbsp;
              </div>
            </div>
            <div class="margin2"></div>
            <div class="count">
              <p>-<%= index + 1 %> -</p>
            </div>
            <div class="update-id"><%= entry.id %></div>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_update-form.html.erb
<div class="hideforms">
<form name="updateForm" class="new_update" id="new_update" data-remote="true" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">
  <input id="update_body" type="text" name="update[body]">
  <button name="button" type="submit" id="update_button">submit</button>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
</form>

app/views/shared/_zero-entries.html.erb
  <!-- code only runs if todays entry hasnt been made -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 col-lg-6 col-lg-offset-3">
            <div class="entries">
              <%= render :partial => 'shared/new-dropdown' %>
            <div class="button-wrapper">
              <div class="carousel__button--next"></div>
              <div class="carousel__button--prev"></div>
            </div>
            <div class="title">
              <div class="subtitle">
                    <%= @user.name.capitalize %>'s Diary
              </div>
              <div class="date">

                    <% date = Time.now.to_s %>
                    <%= Date.parse(date).strftime("%m/%d/%Y")%>

              </div>
            </div>
              <div class="divider div-transparent div-dot"></div>
              <!-- This is where you enter text  -->
              <div contenteditable="true" class="entry">
                &nbsp;
              </div>
              <div class="margin"></div>
              <div class="count">
                <p>- <%=@user.entries.count + 1  %> -</p>
              </div>
            </div>
          </div>
        </div>
      </div>


<!-- Javascript injects content into this form and saves it as an entry instance -->
<div class="form">
  <%= form_for @entry do |f| %>
  <%= f.text_field :body, id: "entry_body" %>
  <%= f.button :submit, id: "button" %>
  <% end %>
</div>